### location

POST {{url}}/api/location
Content-Type: application/json

{
  "apikey": "{{api-key}}",
  "name": "Cezary",
  "surname": "Żurek"
}

### accesslevel

POST {{url}}/api/accesslevel
Content-Type: application/json

{
  "apikey": "{{api-key}}",
  "name": "Cezary",
  "surname": "Żurek",
  "birthYear": 1987
}

### nominatim

GET https://nominatim.openstreetmap.org/search?city=Zabrze&country=Poland&format=json

### railway

POST {{url}}/verify
Content-Type: application/json

{
  "apikey": "{{api-key}}",
  "task": "railway",
  "answer": {
    "action": "help"
  }
}

### railway reconfigure

POST {{url}}/verify
Content-Type: application/json

{
  "apikey": "{{api-key}}",
  "task": "railway",
  "answer": {
    "action": "reconfigure",
    "route": "fsdf"
  }
}


### mailbox

POST {{url}}/api/zmail
Content-Type: application/json

{
  "apikey": "{{api-key}}",
  "action": "help",
  "page": 1
}